export const CATEGORIES_ACTION_TYPES = {
  FEACH_CATEGORIES_START: 'categories/FEACH_CATEGORIES_START',
  FEACH_CATEGORIES_SUCCESS: 'categories/FEACH_CATEGORIES_SUCCESS',
  FEACH_CATEGORIES_FAILED: 'categories/FEACH_CATEGORIES_FAILED'
};
